swagger: '2.0'
info:
  description: Набор сервисов для учета на предприятии /ООО Ромашка/
  version: "1.0.0"
  title: RestApi

produces:
  - application/json
  - application/xml
  - application/text

basePath: "/api"

paths:

  /reports/receipt/{format}:
    get:
      summary: Получить список рецептов
      operationId: main.reports_receipt
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка
    parameters:
      - name: format
        in: path
        description: Уникальный код формата
        required: true
        type: integer

  /reports/nomenclature/{format}:
    get:
      summary: Получить список номенклатур
      operationId: main.reports_nomenclature
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка
    parameters:
      - name: format
        in: path
        description: Уникальный код формата
        required: true
        type: integer

  /reports/group/{format}:
    get:
      summary: Получить список групп номенклатуры
      operationId: main.reports_group
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка
    parameters:
      - name: format
        in: path
        description: Уникальный код формата
        required: true
        type: integer

  /reports/range/{format}:
    get:
      summary: Получить список единиц измерения
      operationId: main.reports_range
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка
    parameters:
    - name: format
      in: path
      description: Уникальный код формата
      required: true
      type: integer

  /reports/formats:
    get:
      summary: Получить список форматов для отчетов
      operationId: main.formats
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка

  /api/filter/{domain}:
    post:
      summary: Фильтрация данных по домену
      operationId: main.filter_data  # Убедитесь, что указано корректное имя функции
      consumes:
        - application/json
      produces:
        - text/plain
      parameters:
        - in: path
          name: domain
          required: true
          description: Индекс домена, который нужно фильтровать (например, 0 для "nomenclature_model")
          type: string
        - in: body
          name: body
          required: true
          description: Модель фильтрации данных
          schema:
            type: object
            additionalProperties: true
      responses:
        200:
          description: Успешная фильтрация
          schema:
            type: string
            description: Отфильтрованные данные
        400:
          description: Ошибка валидации данных
        500:
          description: Внутренняя ошибка сервера
