swagger: '2.0'
info:
  description: Набор сервисов для учета на предприятии /ООО Ромашка/
  version: "1.0.0"
  title: RestApi

produces:
  - application/json
  - application/xml
  - application/text

basePath: "/api"

paths:

  /reports/receipt/{format}:
    get:
      summary: Получить список рецептов
      operationId: main.reports_receipt
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка
    parameters:
      - name: format
        in: path
        description: Уникальный код формата
        required: true
        type: integer

  /reports/nomenclature/{format}:
    get:
      summary: Получить список номенклатур
      operationId: main.reports_nomenclature
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка
    parameters:
      - name: format
        in: path
        description: Уникальный код формата
        required: true
        type: integer

  /reports/group/{format}:
    get:
      summary: Получить список групп номенклатуры
      operationId: main.reports_group
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка
    parameters:
      - name: format
        in: path
        description: Уникальный код формата
        required: true
        type: integer

  /reports/range/{format}:
    get:
      summary: Получить список единиц измерения
      operationId: main.reports_range
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка
    parameters:
    - name: format
      in: path
      description: Уникальный код формата
      required: true
      type: integer

  /reports/formats:
    get:
      summary: Получить список форматов для отчетов
      operationId: main.formats
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка

  /api/filter/type:
    get:
      summary: Получить список типов фильтрации
      operationId: main.filter_type
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                  description: Имя фильтра
                value:
                  type: integer
                  description: Значение фильтра
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка

  /api/filter/list/{domain}/{filter_type}:
    post:
      summary: Получить список данных, отфильтрованных по типу
      operationId: main.filter_data_list
      consumes:
        - application/json
      produces:
        - text/plain
      parameters:
        - name: domain
          in: path
          description: Уникальный код домена
          required: true
          type: string
        - name: filter_type
          in: path
          description: Тип фильтрации
          required: true
          type: string
        - name: body
          in: body
          description: JSON данные для фильтрации
          required: true
          schema:
            type: object
            additionalProperties: true
      responses:
        200:
          description: OK
          schema:
            description: Отфильтрованные данные
        400:
          description: Ошибка валидации данных
        500:
          description: Внутренняя ошибка сервера


  /api/warehouse_transaction/{filter_type}:
    post:
      summary: Get warehouse transaction
      operationId: main.get_warehouse_transaction
      consumes:
        - application/json
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка
      parameters:
        - name: "body"
          in: "body"
          description: "JSON объект с двумя полями: object1 и object2"
          required: true
          schema:
            type: "object"
            required:
              - warehouse
              - nomenclature
            properties:
              warehouse:
                type: "object"
                description: "Первый объект для обработки"
                example: {  }
              nomenclature:
                type: "object"
                description: "Второй объект для обработки"
                example: {  }

  /api/warehouse_turnover/{filter_type}:
    post:
      summary: Получение данных об оборотах на складе.
      description: Создаёт и возвращает информацию о складских оборотах для заданного склада и номенклатуры.
      operationId: main.get_warehouse_turnover
      parameters:
        - name: "body"
          in: "body"
          description: "JSON объект с двумя полями: object1 и object2"
          required: true
          schema:
            type: "object"
            required:
              - warehouse
              - nomenclature
            properties:
              warehouse:
                type: "object"
                description: "Первый объект для обработки"
                example: { }
              nomenclature:
                type: "object"
                description: "Второй объект для обработки"
                example: { }
      produces:
        - application/text
      responses:
        200:
          description: OK
          schema:
            type: object
        500:
          description: Ошибка на сервере
        default:
          description: Неизвестная ошибка
